services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
    restart: unless-stopped

    ports:
      - "53:53/tcp"
      - "53:53/udp"
    

    environment:
      TZ: "America/Chicago"
      FTLCONF_webserver_api_password: "${PIHOLE_WEBPASSWORD}"
      FTLCONF_dns_listeningMode: "all"
    networks:
      - default
      - proxy
    volumes:
      - pihole_config:/etc/pihole

    cap_add:
      - NET_ADMIN

volumes:
  pihole_config:
networks:
  proxy:
    external: true
