- Learning:
  - ChatGPT:
    - href: https://chat.openai.com

  - Cisco:
    - href: https://learningnetwork.cisco.com

  - Microsoft Learn:
    - href: https://learn.micrsoft.com

  - Splunk Docs:
    - href: https://docs.splunk.com

  - Wazuh Docs:
    - href: https://documentation.wazuh.com
