- Learning:
    - Microsoft Learn:
        - href: https://learn.microsoft.com

    - Cisco:
        - href: https://learningnetwork.cisco.com

    - Splunk Docs:
        - href: https://docs.splunk.com

    - Wazuh Docs:
        - href: https://documentation.wazuh.com

- Career:
    - LinkedIn:
        - href: https://linkedin.com

    - Indeed:
        - href: https://indeed.com

    - USAJobs:
        - href: https://usajobs.gov

    - ClearanceJobs:
        - href: https://clearancejobs.com