services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    networks:
      - default
      - proxy
    volumes:
      - /home/randy/docker/homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      PUID: "1000"
      PGID: "1000"
      HOMEPAGE_ALLOWED_HOSTS: "*"
    restart: unless-stopped
networks:
  proxy:
    external: true
