services:

  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: unless-stopped
    command:
      - "-config.file=/etc/loki/loki-config.yml"
    volumes:
      - ./loki/loki-config.yml:/etc/loki/loki-config.yml:ro
      - /var/lib/loki:/loki
    networks:
      - logging
      - monitoring

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    restart: unless-stopped
    command:
      - "run"
      - "--storage.path=/var/lib/alloy/data"
      - "/etc/alloy/config.alloy"
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy:ro
      - /var/log/journal:/var/log/journal:ro
      - /run/log/journal:/run/log/journal:ro
      - /etc/machine-id:/etc/machine-id:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - alloy_data:/var/lib/alloy
    networks:
      - logging

volumes:
  alloy_data:

networks:
  logging:
    driver: bridge

  monitoring:
    external: true
    name: monitoring_monitoring
